[package]
name = "process_utils"
version = "1.0.0"
edition = "2024"

[dependencies]
errors_with_context = "1.2.0"
tokio = { version = "1.45.1", default-features = false, features = ["test-util", "process", "io-util"] }
