[package]
name = "vpn"
version = "0.1.0"
edition = "2024"

[dependencies]
errors_with_context = { version = "1.2.0", features = ["send"] }
process_utils = { path = "../process_utils"}
tokio = { version = "*", default-features = false, features = ["rt-multi-thread", "macros", "fs"] }
