[package]
name = "jetbrains_setup"
version = "0.1.0"
edition = "2024"

[dependencies]
errors_with_context = "1.2.0"
process_utils = { path = "../process_utils"}
tokio = { version = "*", default-features = false, features = ["rt", "macros", "fs"] }
log = "0.4.27"
env_logger = "0.11.8"
